### ISSUE TITLE
Error when logger is used rarely.

### ISSUE THREAD

**Issue by tyraeltyro** [DataDog/serilog-sinks-datadog-logs#4]
Hi, 
When TCPClient is connected but not used often enough, this error occurs:
Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

StackTrace:
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)

**Comment by tyraeltyro** [comment]
I manage to fix this by runing Close() Methode after the message is sended in DatadogClient.

**Comment by ajacquemot** [comment]
Hi,

Thanks for opening this issue, we've just released a new version with the fixed just attached.
Closing the ticket.

Cheers
