### ISSUE TITLE
The sink does not handle connection errors

### ISSUE THREAD

**Issue by alexander-frolov** [DataDog/serilog-sinks-datadog-logs#8]
Hello,

We are experiencing an issue while running the Sink in a .NET Core project executed in a Linux Docker container in AWS.

It appears that if the connection is dropped because of some reson, the sink will not attempt to re-establish it while sending new messages. As a result, after several minutes of running our service, it will stop delivering log messages to the Datadog.

In the code below, if an error occurs while writing to the stream and the stream cannot be used anymore, the sink will not re-create the stream and will continue attempting to write into it.

``` csharp
try
{
    SelfLog.WriteLine("Sending payload to Datadog: {0}", payload);
    byte[] data = UTF8.GetBytes(payload);
    _stream.Write(data, 0, data.Length);
    return;
}
catch (Exception e)
{
    SelfLog.WriteLine("Could not send data to Datadog: {0}", e);
}
```

Here are some errors we see in the Serilog SelfLog:

```
20:46:06	2018-10-19T20:46:06.1343355Z Could not send data to Datadog: System.IO.IOException: Unable to write data to the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out
20:46:06	at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
20:46:06	--- End of inner exception stack trace ---
20:46:06	at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
20:46:06	at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
20:46:06	at System.Net.Security.SslStreamInternal.WriteAsyncChunked[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
20:46:06	at System.Net.Security.SslStreamInternal.<WriteAsyncInternal>g__ExitWriteAsync|35_0[TWriteAdapter](ValueTask task)
20:46:06	at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
20:46:06	at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
20:46:06	at Serilog.Sinks.Datadog.Logs.DatadogClient.WriteAsync(String payload)
```

```
20:46:07	2018-10-19T20:46:07.1655678Z Could not send data to Datadog: System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
20:46:07	at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
20:46:07	--- End of inner exception stack trace ---
20:46:07	at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
20:46:07	at System.Net.Security.SslStreamInternal.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
20:46:07	at System.Net.Security.SslStreamInternal.WriteAsyncChunked[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
20:46:07	at System.Net.Security.SslStreamInternal.<WriteAsyncInternal>g__ExitWriteAsync|35_0[TWriteAdapter](ValueTask task)
20:46:07	at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
20:46:07	at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
20:46:07	at Serilog.Sinks.Datadog.Logs.DatadogClient.WriteAsync(String payload)
```

```
21:09:28	2018-10-19T21:09:28.0784566Z Could not send data to Datadog: System.NotSupportedException: The WriteAsync method cannot be called when another write operation is pending.
21:09:28	at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
21:09:28	at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
21:09:28	at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
21:09:28	at Serilog.Sinks.Datadog.Logs.DatadogClient.WriteAsync(String payload)
```

Probably related to the following issue: [https://github.com/dotnet/corefx/issues/32634](https://github.com/dotnet/corefx/issues/32634)

**Comment by NBParis** [comment]
Hello @alexander-frolov ,

Thanks a lot for raising this issue and helping us improve the SeriLog sink.
We will definitely try to replicate and look at the issue you linked.

Thanks again for all those details.
